### ISSUE TITLE
Filing version 2017v2.2 incompatible

### ISSUE THREAD

**Issue by RonHolbrook** [jsfenfen/990-xml-reader#21]
Looks like IRS may have released a new version of the xml files.
IRSx doesn't seem to like them much.

$ /home/ec2-user/.local/bin/irsx --format=csv 201841359349103204 >> test.csv
$ cat test.csv
Filing version 2017v2.2 isn't supported for this operation
object_id,form,line_number,description,value,variable_name,xpath,in_group,group_name,group_index

**Comment by jsfenfen** [comment]
Hey @RonHolbrook I updated for 2017 in [0.2.1](https://github.com/jsfenfen/990-xml-reader/blob/master/CHANGELOG.md#021---2018-05-04), but you gotta update your installation to get the changes. Can you try something like `pip install irsx --upgrade`.
